---
title: Working with Data Duplication in Postgres
slug: postgres-duplicates
date: "2024-11-02"
description: How to check, analyze and remove data duplication in Postgres
tags:
  - Database
knitr:
  opts_chunk:
    collapse: true
    comment: "#"
draft: true
---

## Define Duplication

In relational databases, data duplication usually means multiple records that have the same values in all columns. They are considered an anomaly, and we want to handle the duplicated records specially, such as adding a flag, giving them less weight, or keeping only one row per group.

However, the definition of duplication varies by domain. If you are running an online survey, a participant (identified by IP address) can fill out the form multiple times, but we might only want to count their last submission. Then all previous submissions are duplicates, regardless of whether the answers differ.

In this post, we will consider a table for storing the quiz submissions of students in a university class. Each row represents a student's submission for a quiz, along with the score and the submission date. A student may submit the same quiz multiple times.


## Check Duplication




```{r}
#| include: false

db <- DBI::dbConnect(RPostgres::Postgres(), dbname = "postgres", host = "localhost", port = 5432, user = "postgres", password = "postgres")

max_rows <- 10
knitr::knit_engines$set(sql = function(options) {
  # Get the SQL code from options
  sql <- paste(options$code, collapse = "\n")
  res <- DBI::dbSendQuery(db, sql)
  data <- DBI::dbFetch(res, n = max_rows)
  DBI::dbClearResult(res)

  # Wrap in code block
  output <- c("```sql", sql, "", paste("-- Output: ", nrow(data), "rows"), knitr::kable(data),  "```")

  # Return the formatted output
  paste(output, collapse = "\n")
})

knitr::opts_chunk$set(connection = "db")
```

<table>
<caption>The <code>quiz_submissions</code> table: a student can submit the same quiz multiple times</caption>
<thead><tr><th>id</th><th>student_id</th><th>quiz_id</th><th>score</th><th>date</th></tr></thead>
<tbody>
<tr><td>1</td><td>1</td><td>1</td><td>90</td><td>2024-10-30</td></tr>
<tr><td>2</td><td>1</td><td>1</td><td>80</td><td>2024-10-30</td></tr>
<tr><td>3</td><td>2</td><td>1</td><td>70</td><td>2024-10-30</td></tr>
<tr><td>4</td><td>3</td><td>2</td><td>100</td><td>2024-10-30</td></tr>
<tr><td>5</td><td>4</td><td>1</td><td>80</td><td>2024-11-01</td></tr>
<tr><td>6</td><td>2</td><td>2</td><td>90</td><td>2024-11-02</td></tr>
</tbody>
</table>

```{sql, include=FALSE}
DROP TABLE IF EXISTS quiz_submissions;
```

```{sql}
CREATE TABLE quiz_submissions (
   id INTEGER PRIMARY KEY,
   student_id INTEGER NOT NULL,
   quiz_id INTEGER NOT NULL,
   score INTEGER NOT NULL,
   date DATE NOT NULL
);
```

```{sql, include=FALSE}
-- Insert the data
INSERT INTO quiz_submissions (id, student_id, quiz_id, score, date)
VALUES
   (1, 1, 1, 90, '2024-10-30'),
   (2, 1, 1, 80, '2024-10-30'),
   (3, 2, 1, 70, '2024-10-30'),
   (4, 3, 2, 100, '2024-10-30'),
   (5, 4, 1, 80, '2024-11-01'),
   (6, 2, 2, 90, '2024-11-02');
```


## Deduplication

### The Limitations of `SELECT DISTINCT`

`SELECT DISTINCT` is a query modifier, available in most relational databases, that removes rows whose columns are all identical to those of another row.



To get the unique list of students who have submitted a quiz, we write the following query:

```{sql}
SELECT DISTINCT student_id
from quiz_submissions;
```

How about the unique combinations of students and their scores? Just add the `score` column to the column set:

```{sql}
SELECT DISTINCT student_id, score
FROM quiz_submissions;
```

Things get more complicated when we deduplicate rows within a subset instead of the entire table. For example, say we want the latest score of each student in each quiz. This is impossible with a single `SELECT DISTINCT` statement: once you put all 3 columns in `SELECT DISTINCT`, you get all the rows back.

This leads to a major downside of `SELECT DISTINCT`: you must use the same set of columns for both duplication checks and column selection. So you can't get unique rows based on specific columns while getting the associated data from other columns. For example,


Another problem of `SELECT DISTINCT` is that you are limited to using the same column set to do both duplication checks and column selection. For example, if we are asking the question ""

Postgres offers an additional `DISTINCT ON` clause that gives you more flexibility.

### `DISTINCT ON` Clause
