project:
  output-dir: _output
execute:
  freeze: auto
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

format:
  gfm:
    variant: +yaml_metadata_block
    filters:
      - filters/code.lua
      - filters/image.lua
      - filters/headings.lua
