project:
  output-dir: ../content/posts
execute:
  freeze: auto
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

format:
  gfm:
    variant: +yaml_metadata_block
    filters:
      - my-filter
