project:
  output-dir: ../content/posts
allowEmptyValues: true
execute:
  freeze: auto
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true


format:
  gfm:
    number-sections: true
    variant: +yaml_metadata_block
