---
title: Structural Pattern Matching in Python 3.10
slug: python310-pattern-matching
date: '2022-02-20'
description: |
    Python 3.10 added the _py`match case`_ statement for structural pattern matching. This article reviews the syntax and shows some practical examples.
tags:
    - Python
---

```{r}
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

[Structural Pattern Matching](https://www.python.org/dev/peps/pep-0634/) is a new feature introduced in Python [3.10](https://docs.python.org/3/whatsnew/3.10.html), and perhaps the most intriguing one. It takes an object to inspect (following _py`match`_) and multiple patterns to match against (following one or more _py`case`_). If there is a match, a pattern-specific code block runs. The basic syntax is:

<!-- ```{r, include = FALSE}
ymisc::set_knitr_options()
library(reticulate)
Sys.setenv(RETICULATE_PYTHON = "/opt/homebrew/Cellar/python@3.10/3.10.5/bin/python3")
``` -->


```{python}
error_code = 403
match error_code:
    case 400:
        print("Bad request")
    case 403:
        print("Unauthorized")
    case 500:
        print("Internal server error")
# !callout[/case _/] the default case when none of the above matches :right
    case _:
        print("Something's wrong with the Internet")
```

Here, we check case by case whether `error_code` equals a value; if it's not one of `400`, `403` or `500`, `_` acts as a catch-all wildcard. Also, pattern matching stops when it hits a match, so each `case` should be independent.



To run the examples in this article, make sure you are using Python 3.10 or higher.

```{python}
import sys
sys.version
```


## Pattern Matching as a Replacement for `switch` Statements

The most obvious use of pattern matching is implementing the `switch ... case` statements found in many other programming languages, as a replacement for multiple if-else statements. Imagine we are building a game with a `move` function for controlling figure movement:

```python
def move(self, direction):
    match direction:
        case "up":
            self.move_up()
        case "down":
            self.move_down()
        case "left":
            self.move_left()
        case "right":
            self.move_right()
```

## Match Against Dictionaries and Lists

The real power of pattern matching resides in destructuring data structures like lists and dictionaries.

```{python}
match {"first_name": "Jane", "last_name": "Doe", "middle_name": ""}:
    case {"first_name": first_name , "last_name": last_name}:
        print(first_name, last_name)
```

In the example above, the pattern says the object should contain the keys "first_name" and "last_name"; if it matches, their values are captured into the variables `first_name` and `last_name`. Note that for a dictionary, structural pattern matching matches the structure instead of the exact content: the pattern matches as long as "first_name" and "last_name" are among the object's keys, and any unmentioned keys, like "middle_name", are ignored.

For a more advanced example, suppose we are working with the [SpaceX API](https://docs.spacexdata.com/) to retrieve launch data. An individual launch record looks like this:

```json
{
        "flight_number": 1,
        "mission_name": "FalconSat",
        "upcoming": false,
        "launch_year": "2006",
        "launch_date_unix": 1143239400,
        "rocket": {
            "rocket_id": "falcon1",
            "rocket_name": "Falcon 1",
        },
        "details": "Engine failure at 33 seconds and loss of vehicle",
        //... other fields
}
```

We only want the fields `mission_name`, `rocket_name` and `details`:


```{python}
#| collapse: false
#| class-output: json
#| comment: ""
import requests
import json
import pprint
res = requests.get("https://api.spacexdata.com/v3/launches?limit=3")
data = res.json()
out = []
for launch in data:
    match launch:
        case {"mission_name": mname, "rocket": {"rocket_name": rname}, "details": details}:
            out.append({"mission_name": mname, "rocket_name": rname, "details": details})

print(json.dumps(out, indent = 2))
```

Here, we not only match the top-level keys `mission_name` and `details`, but also use a nested pattern to extract the rocket name.

You can also match on a list.

```{python}
match [1, 2, 3]:
    case [1, 2]:
        print("match 1")
# !callout[/\*rest/] match the the rest of elements
    case [2, *rest]:
        print("match 2")
        print(rest)
# !callout[/\*other/] match elements except the last one
    case[*other, last]:
        print("match 3")
        print(last)
        print(other)
```

I mentioned that pattern matching on a dict does not require us to declare all fields explicitly. Lists are different: we have to declare all elements, which is why match 1 fails. Match 2 attempts to use the `*` syntax to capture all values after 2 into a list called `rest`. This helps when the list is very large and it's impossible to exhaust all elements, or when we simply don't care about some elements. However, the second pattern does not specify the correct order, as 2 is not the first element in the matching object. Match 3 captures all elements but the last into `other`, and assigns the last element to `last`.


It's also possible to express `or` logic with `|` in a case statement. For example, we may add a `case 401 | 403 | 404: "Not allowed"` statement to our first example. Here is another example from the PEP:

```python
match command.split():
    ... # Other cases
    case ["north"] | ["go", "north"]:
        current_room = current_room.neighbor("north")
    case ["get", obj] | ["pick", "up", obj] | ["pick", obj, "up"]:
        ... # Code for picking up the given object
```

Literal patterns can also be captured using the `as` keyword:

```python
match command.split():
    case ["go", ("north" | "south" | "east" | "west") as direction]:
        current_room = current_room.neighbor(direction)
```

## Add Conditions

Pattern matching allows if conditions the same way as list comprehensions: we can append an _py`if ... else`_ clause like so:


```python
all_directions = ["up", "down"]

match commad.split():
    case ["go", direction] if direction in all_directions:
        move(direction)
    case ["go", _]:
        print("direction not supported")
```


For conditions that check whether an object is of a data type, we can directly use the class creator function:

```{python}
#| error: true
def sum_list(numbers):
    match numbers:
        case []:
            return 0
        case [int(first) | float(first), *rest]:
            return first + sum_list(rest)
        case _:
            raise ValueError(f"Can only sum lists of numbers")

sum_list([1, 2, 3])
sum_list([1, "2", 3])
```

Here _py`int(first) | float(first)`_ checks whether the first element is an integer or float. The next example uses a `dataclass`-based pattern along with its attributes:

```{python}
from dataclasses import dataclass

@dataclass
class Point:
    x: float
    y: float

p = Point(x = 1, y = 1)
# data class for validation
match p:
    case Point(x = x):
        print(x)
```


In general, any class can be used for validation. This is also called a **class pattern**.

## Matching Against Constants

Be careful when matching constants, since it's common to store a constant in a variable and then use it in `case`. The following code will not work:

```python
direction = "up"

match "down":
# !callout[/direction/] capture "up" into the variable `direction` :right
    case direction:
        print("match")
    case _:
        print("no match")
```

We are trying to match the value "up", but Python interprets it as a capture pattern that stores whatever the match object is into the variable `direction`, so we are effectively overriding `direction` (recall the list matching example) and the first case always matches. Python rejects this with the error message `SyntaxError: name capture 'direction' makes remaining patterns unreachable`.

Instead of matching literal values, we can use an enum type for constant matching:

```{python}
import enum
class Direction(str, enum.Enum):
    up = "up"
    down = "down"

match "down":
    case Direction.up:
        print("match 1")
    case Direction.down:
        print("match 2")
    case _:
        print("match 3")
```
