project:
  output-dir: ../content
  render:
    - "*.qmd"
  post-render:
    - scripts/process_post_quarto.py
execute:
  freeze: auto
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

format:
  gfm:
    variant: +yaml_metadata_block
    filters:
      - scripts/filters/code.lua
      - scripts/filters/image.lua
      - scripts/filters/headings.lua
